name: ✨ Feature Request
description: Suggest a new feature or enhancement for NeuroQuantumDB
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have searched the [existing issues](https://github.com/twoh-me/NeuroQuantumDB/issues) to make sure this feature has not already been requested.
          required: true
        - label: I have read the [documentation](https://github.com/twoh-me/NeuroQuantumDB/tree/main/docs) to confirm this feature doesn't already exist.
          required: false

  - type: dropdown
    id: component
    attributes:
      label: Target Component
      description: Which component would this feature affect?
      multiple: true
      options:
        - neuroquantum-core
        - neuroquantum-api
        - neuroquantum-qsql
        - neuroquantum-cluster
        - neuroquantum-wasm
        - CLI
        - Configuration
        - Documentation
        - Tooling/DevEx
        - Other
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Functionality
        - Performance Improvement
        - Developer Experience
        - Query Language (QSQL)
        - API Enhancement
        - Clustering/Distributed
        - Security
        - Monitoring/Observability
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem you're trying to solve. What pain point or limitation are you experiencing?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. Be as specific as possible.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: textarea
    id: api
    attributes:
      label: Proposed API / Syntax
      description: If applicable, show how you envision the API or QSQL syntax for this feature.
      render: rust
      placeholder: |
        // Example API usage or QSQL syntax
        
        // Rust API
        db.new_feature().with_option(true).execute()?;
        
        // Or QSQL
        SELECT * FROM table WHERE quantum_feature(...);

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases that would benefit from this feature.
      placeholder: |
        1. When building a real-time analytics dashboard...
        2. When migrating from another database...

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes?
      options:
        - "No"
        - "Yes, minor API changes"
        - "Yes, significant changes required"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Willing to Contribute
      description: Are you willing to help implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "No, but I can provide more details if needed"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, examples, or references about the feature request here.
