name: 🔒 Security Vulnerability
description: Report a security vulnerability (for non-critical issues only - for critical vulnerabilities, please email security@twoh-me.com)
title: "[Security]: "
labels: ["security", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Security Notice
        
        **For critical security vulnerabilities**, please do NOT create a public issue. Instead, please report them privately via:
        - Email: security@twoh-me.com
        - GitHub Security Advisory: [Report a vulnerability](https://github.com/twoh-me/NeuroQuantumDB/security/advisories/new)
        
        This template is for **non-critical security issues** that can be discussed publicly.

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Acknowledgment
      description: Please confirm the following before proceeding.
      options:
        - label: I confirm this is NOT a critical security vulnerability that could be actively exploited.
          required: true
        - label: I have reviewed the [security policy](https://github.com/twoh-me/NeuroQuantumDB/security/policy).
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Category
      description: What category does this security issue fall under?
      options:
        - Authentication/Authorization
        - Input Validation
        - Denial of Service
        - Information Disclosure
        - Cryptographic Issue
        - Dependency Vulnerability
        - Configuration Issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - neuroquantum-core
        - neuroquantum-api
        - neuroquantum-qsql
        - neuroquantum-cluster
        - neuroquantum-wasm
        - Docker Configuration
        - Kubernetes Deployment
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue. Be specific but avoid sharing exploit details publicly.
      placeholder: |
        Describe the security concern...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: Describe the potential impact if this vulnerability were exploited.
      placeholder: |
        An attacker could potentially...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce (if safe to share publicly).
      placeholder: |
        1. Configure the system with...
        2. Send a request to...
        3. Observe that...

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have ideas for how to fix this issue, please share them.
      placeholder: |
        The issue could be mitigated by...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide relevant environment details.
      value: |
        - NeuroQuantumDB version: 
        - Deployment type (Docker/K8s/Binary): 
        - OS: 

  - type: textarea
    id: references
    attributes:
      label: References
      description: Include any CVEs, CWEs, or other references related to this issue.
      placeholder: |
        - CWE-XXX: ...
        - Related CVE: ...
        - OWASP reference: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the security issue.
